export const GENRES = [
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 10751, name: "Family" },
  { id: 12, name: "Adventure" },
  { id: 14, name: "Fantasy" },
  { id: 10749, name: "Romance" },
  { id: 28, name: "Action" },
  { id: 80, name: "Crime" },
  { id: 18, name: "Drama" },
  { id: 53, name: "Thriller" },
  { id: 36, name: "History" },
  { id: 878, name: "Science Fiction" },
  { id: 9648, name: "Mystery" },
  { id: 10752, name: "War" },
  { id: 10769, name: "Foreign" },
  { id: 10402, name: "Music" },
  { id: 27, name: "Horror" },
  { id: 99, name: "Documentary" },
  { id: 37, name: "Western" },
  { id: 10770, name: "TV Movie" },
];
